### ISSUE TITLE
Potential issue in README example

### ISSUE THREAD

**Issue by ibnesayeed** [BryanSchuetz/jekyll-deploy-gh-pages#18]
Are these `GITHUB_REPOSITORY` and `GITHUB_ACTOR` configurations intentional in the README Example? These values are available as [environment variables in all runner environments](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/using-environment-variables), so why would we namespace them under `secrets` other than the `GITHUB_TOKEN` that is created by the user?

```yml
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
```
